// <auto-generated />
using System;
using DaoPlanImport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaoPlanImport.Migrations
{
    [DbContext(typeof(DaoPlanDbContext))]
    [Migration("20260421204712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaoPlanImport.Entities.JobPolygon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiomNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LocationCount")
                        .HasColumnType("int");

                    b.Property<string>("Polygon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DiomNr", "JobNr")
                        .IsUnique()
                        .HasFilter("[DiomNr] IS NOT NULL AND [JobNr] IS NOT NULL");

                    b.ToTable("JobPolygons");
                });

            modelBuilder.Entity("DaoPlanImport.Entities.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABONNAVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABONNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRBEMAERK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRESSERET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFLOTEKST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BARCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BREDDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONAVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DARTID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIOMNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOERKODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETAGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETAGELEVERING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FORDNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FULD_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GADENAVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GADESORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOEJDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOMEBOX_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HUSNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HUSNRSORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HUSN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JOBADRNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOBNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOBSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOSTNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONTO_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LABELLESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LABELSLEVERING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAENGDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIGASORTNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIGA_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LITRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOEGLEBUNDTHUL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAKKE_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHOTO_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSTDISTRIKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSTNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIORITET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUKTANTAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUKTKORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUKTNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAEKKEFOELGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECEIPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REKLAMATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIDELEJLIGHED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SORT_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOURCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STANGNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STANGSUFFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STEDBETEGNELSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPPADRESSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TILGANG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAEGT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VEJBEMAERK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("ImportDate");

                    b.HasIndex("FileName", "ImportDate");

                    b.ToTable("Ligas");
                });
#pragma warning restore 612, 618
        }
    }
}
